name: tf2.2_env
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2025.11.12=h4c7d964_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cudatoolkit=10.1.243=hc75346c_13
  - cudnn=7.6.5.32=h36d860d_1
  - openssl=1.1.1w=hcfcfb64_0
  - pip=22.3.1=py37haa95532_0
  - python=3.7.16=h6244533_0
  - setuptools=65.6.3=py37haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.38.4=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - pip:
      - absl-py==2.1.0
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - astunparse==1.6.3
      - attrs==24.2.0
      - babel==2.14.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - bleach==6.0.0
      - cachetools==4.2.4
      - cffi==1.15.1
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - comm==0.1.4
      - cycler==0.11.0
      - daal==2021.5.0
      - daal4py==2021.5.0
      - debugpy==1.7.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - exceptiongroup==1.3.1
      - fastjsonschema==2.21.2
      - fonttools==4.38.0
      - gast==0.3.3
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.62.3
      - h5py==2.10.0
      - idna==3.10
      - imageio==2.31.2
      - imgaug==0.2.9
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - imutils==0.5.2
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.3.2
      - json5==0.9.16
      - jsonschema==4.17.3
      - jupyter==1.1.1
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==4.12.0
      - jupyter-lsp==1.5.1
      - jupyter-server==1.24.0
      - jupyterlab==3.5.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.16
      - keras==2.3.1
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.1.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - nbclassic==1.2.0
      - nbclient==0.7.4
      - nbconvert==7.6.0
      - nbformat==5.8.0
      - nest-asyncio==1.6.0
      - networkx==2.6.3
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numpy==1.18.5
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==1.3.5
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pipdeptree==2.9.6
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.48
      - protobuf==4.24.4
      - psutil==7.2.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygments==2.17.2
      - pyparsing==3.1.4
      - pyrsistent==0.19.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.3.0
      - pywin32==308
      - pywinpty==2.0.10
      - pyyaml==6.0.1
      - pyzmq==26.2.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scikit-learn-intelex==2021.5.0
      - scipy==1.7.3
      - seaborn==0.12.2
      - send2trash==1.8.3
      - shapely==2.0.7
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.3.2
      - tbb==2021.13.1
      - tensorboard==2.2.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.2.2
      - tensorflow-estimator==2.2.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tornado==6.2
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.15
      - wrapt==1.16.0
      - zipp==3.15.0
